apiVersion: v1
kind: Secret
metadata:
    name: microsoft-azure-ad-credentials
type: Opaque
stringData:
    issuerUrl: https://login.microsoftonline.com/{TENANT_ID}/v2.0
    clientId: {CLIENT_ID}
    clientSecret: {CLIENT_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-cookie-secret
type: Opaque
stringData:
    secret: {COOKIE_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
    name: transport-api-credentials
type: Opaque
stringData:
    appId: replaceme
    apiKey: replaceme