apiVersion: v1
kind: Secret
metadata:
    name: microsoft-azure-ad-credentials
type: Opaque
stringData:
    issuerUrl: https://login.microsoftonline.com/6e26a76f-adf1-4e9e-8eea-25f26bf52a0f/v2.0
    clientId: 62b68661-c299-4466-ac70-bf119e919823
    clientSecret: Rm08Q~yExf4lCj6y-ro_BnJvcm_WupBWH94Iybw9
---
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-cookie-secret
type: Opaque
stringData:
    secret: OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w=