apiVersion: v1
kind: ConfigMap
metadata:
    name: oauth2-proxy
data:
    config: |
        http_address="0.0.0.0:4180"
        provider="oidc"
        email_domains=["danielfeathersandbox.onmicrosoft.com"]
        cookie_secure="true"
        redirect_url="https://nginx.lancastrian.dev/oauth2/callback"
        cookie_domains=".lancastrian.dev"
        whitelist_domains=".lancastrian.dev"
        reverse_proxy="true"
        upstreams="static://202"
        skip_provider_button="false"