kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth2-proxy
  labels:
    app: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: 143364350185.dkr.ecr.eu-west-2.amazonaws.com/danielfeather/oauth2-proxy:latest
        args:
        - --config=/etc/oauth2proxy/oauth2-proxy-config
        ports:
        - name: web
          containerPort: 4180
        env:
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
              secretKeyRef:
                  name: oauth2-proxy-cookie-secret
                  key: secret
                  optional: false
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
              secretKeyRef:
                name: microsoft-azure-ad-credentials
                key: clientId
                optional: false
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
              secretKeyRef:
                name: microsoft-azure-ad-credentials
                key: clientSecret
                optional: false
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          valueFrom:
              secretKeyRef:
                name: microsoft-azure-ad-credentials
                key: issuerUrl
                optional: false
      volumes:
      - name: oauth2-proxy-config
        configMap:
          name: oauth2-proxy
